#include <bits/stdc++.h>
using namespace std; using u64=uint64_t; using u128=__uint128_t;
string s128(u128 x){if(!x)return"0";string s;while(x){s.push_back('0'+x%10);x/=10;}reverse(s.begin(),s.end());return s;}
bool p2(u128 x,int&k){if(!x||(x&(x-1)))return false;k=0;while((x>>k)!=1)++k;return true;}
bool hit(u128 n,int KMIN,int&K){u128 x=(n&1)?n+1:3*n+2;int k;if(!p2(x,k))return false;if(k>=KMIN&&(k&1)){K=k;return true;}return false;}
struct Node{int j;u64 r,A,C;}; struct Stats{u64 nodes=0,drop=0,leaf=0;int maxj=0,maxsteps=0;u128 peak=0;u64 hs=0;u128 hn=0;int hk=0;};
bool range(u64 L,u64 U,int j,u64 r,u64&mn,u64&mx){u64 M=1ULL<<j, rem=L&(M-1), add=(r>=rem?r-rem:M-(rem-r));if(add>U-L)return false;mn=L+add;u64 remU=U&(M-1),sub=(remU>=r?remU-r:M-(r-remU));mx=U-sub;return mn<=mx;}
bool exact(u64 s,int KMIN,Stats&st){u128 n=s;int q=0;const u128 MAX=~(u128)0;while(n>=s){st.peak=max(st.peak,n);int K;if(hit(n,KMIN,K)){st.hs=s;st.hn=n;st.hk=K;return false;}if(n&1){if(n>(MAX-1)/3){cerr<<"overflow\n";exit(4);}n=(3*n+1)/2;}else n/=2;if(++q>10000){cerr<<"pathlong\n";exit(5);}}st.maxsteps=max(st.maxsteps,q);return true;}
bool cert(u64 L,u64 U,int KMIN,Stats&st){vector<Node>S{{0,0,1,0}};while(!S.empty()){auto d=S.back();S.pop_back();st.nodes++;st.maxj=max(st.maxj,d.j);u64 mn,mx;if(!range(L,U,d.j,d.r,mn,mx))continue;u128 den=(u128)1<<d.j,y0=((u128)d.A*mn+d.C)/den,y1=((u128)d.A*mx+d.C)/den;for(int K=(KMIN|1);K<127;K+=2){u128 P=(u128)1<<K,T[2]={P-1,(P-2)/3};for(auto t:T){if(t<y0||t>y1)continue;u128 rhs=den*t;if(rhs<d.C)continue;rhs-=d.C;if(rhs%d.A)continue;u128 nn=rhs/d.A;if(nn<mn||nn>mx||nn>numeric_limits<u64>::max())continue;u64 s=(u64)nn,M=1ULL<<d.j;if((s&(M-1))!=d.r)continue;st.hs=s;st.hn=t;st.hk=K;return false;}}if(den>d.A&&(den-d.A)*(u128)mn>d.C){st.drop++;continue;}if(mn==mx||d.j>=36){st.leaf++;if(!exact(mn,KMIN,st))return false;continue;}u64 M=1ULL<<d.j;for(int b=0;b<2;b++){u64 rr=d.r+(b?M:0);u128 num=(u128)d.A*rr+d.C;bool odd=(num>>d.j)&1;u64 A=d.A,C=d.C;if(odd){A*=3;C=3*C+M;}S.push_back({d.j+1,rr,A,C});}}return true;}
int main(int ac,char**av){u64 L=stoull(av[1]),U=stoull(av[2]);int K=stoi(av[3]);Stats st;bool ok=cert(L,U,K,st);cout<<"ok="<<ok<<" interval=["<<L<<","<<U<<"] KMIN="<<K<<" nodes="<<st.nodes<<" drop="<<st.drop<<" leaf="<<st.leaf<<" maxj="<<st.maxj<<" maxsteps="<<st.maxsteps<<" peak="<<s128(st.peak);if(!ok)cout<<" hit_start="<<st.hs<<" hit_state="<<s128(st.hn)<<" K="<<st.hk;cout<<"\n";return ok?0:1;}
