#include <boost/multiprecision/cpp_int.hpp>
#include <unordered_map>
#include <vector>
#include <iostream>
#include <chrono>
#include <cstdint>
#include <algorithm>
using boost::multiprecision::cpp_int;
struct Key{cpp_int J;uint16_t z;uint8_t d;bool operator==(Key const&o)const{return J==o.J&&z==o.z&&d==o.d;}};struct KH{size_t operator()(Key const&k)const noexcept{auto const&b=k.J.backend();size_t h=b.sign()?0x9e3779b97f4a7c15ULL:0x243f6a8885a308d3ULL;for(unsigned i=0;i<b.size();++i){uint64_t x=(uint64_t)b.limbs()[i];h^=x+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);}return h^((size_t)k.z<<8)^k.d;}};
struct Hull{cpp_int lo=0,hi=0;bool ok=false;};static cpp_int fd3(cpp_int const&a){if(a>=0)return cpp_int(a/3);return cpp_int(-((-a+2)/3));}static cpp_int cd3(cpp_int const&a){if(a>=0)return cpp_int((a+2)/3);return cpp_int(-((-a)/3));}
struct Result{bool hit=false,terminal_cap=false,relaxed_start=false;int minH=-1;uint64_t total=0,peak=0,macro_starts=0,macro_steps=0,hull_prune=0,res_prune=0;double secs=0;};
static Result run_t(int A,int E,int t){int P=E-2,Q=A-E,zt=Q-t,n0=(P-1)+zt,B=t+2;Result R;if(t<0||(t&1)||zt<1)return R;int DMAX=1;while((DMAX+1)*DMAX/2<=B)++DMAX;
 std::vector<cpp_int> p3(DMAX+3),Ad(DMAX+2),Bd(DMAX+2),Cd(DMAX+2);p3[0]=1;for(int i=1;i<(int)p3.size();++i)p3[i]=p3[i-1]*3;for(int d=1;d<=DMAX+1;++d){Ad[d]=p3[d]-(cpp_int(1)<<d);Bd[d]=(cpp_int(1)<<d)-1;Cd[d]=p3[d+1]-(cpp_int(1)<<d)-1;}
 std::vector<std::vector<char>> cap(n0+1,std::vector<char>(zt+1,0));cpp_int X2=cpp_int(1)<<(2*A),Y=1;for(int i=0;i<E;++i)Y*=3;cpp_int Y2=Y*Y;std::vector<cpp_int> pp3(P+3);pp3[0]=1;for(int i=1;i<=P+2;++i)pp3[i]=pp3[i-1]*3;for(int n=1;n<=n0;++n)for(int z=1;z<=zt;++z){int pa=n-z;if(pa<0||pa>P-1)continue;cap[n][z]=((cpp_int(1)<<(n+2))*Y2<=pp3[pa+2]*X2);}R.terminal_cap=cap[n0][zt];if(!R.terminal_cap)return R;
 auto idx=[&](int n,int z,int d){return((size_t)n*(zt+1)+z)*(DMAX+2)+d;};size_t G=(size_t)(n0+1)*(zt+1)*(DMAX+2);std::vector<Hull> hull(G);cpp_int Jtar=cpp_int(1)<<(t+3);hull[idx(n0,zt,1)]={Jtar,Jtar,true};
 // ordinary interval future hull
 for(int n=n0-1;n>=1;--n)for(int z=1;z<=std::min(zt,n);++z){int pa=n-z;if(pa<0||pa>P-1||!cap[n][z])continue;for(int d=1;d<=DMAX;++d){if(pa+d>P)continue;Hull out;const int xs[4]={0,1,0,1},ys[4]={0,1,1,0};for(int ii=0;ii<4;++ii){int x=xs[ii],y=ys[ii],nd=d+y-x;if(nd<=0||nd>DMAX)continue;int z2=z+1-x,pa2=pa+x;if(z2<1||z2>zt||pa2>P-1||pa2+nd>P||!cap[n+1][z2])continue;Hull const&hn=hull[idx(n+1,z2,nd)];if(!hn.ok)continue;cpp_int lo,hi;if(!x&&!y){lo=2*hn.lo-Ad[d];hi=2*hn.hi-Ad[d];}else if(x&&y){lo=fd3(2*hn.lo-Bd[d]);hi=cd3(2*hn.hi-Bd[d]);}else if(!x&&y){lo=fd3(2*hn.lo-Cd[d]);hi=cd3(2*hn.hi-Cd[d]);}else{lo=2*hn.lo;hi=2*hn.hi;}if(!out.ok)out={lo,hi,true};else{if(lo<out.lo)out.lo=lo;if(hi>out.hi)out.hi=hi;}}hull[idx(n,z,d)]=std::move(out);}}
 Hull const&hs=hull[idx(1,1,1)];R.relaxed_start=hs.ok&&cpp_int(-13)>=hs.lo&&cpp_int(-13)<=hs.hi;if(!R.relaxed_start)return R;
 // Area-budgeted future residue masks modulo 64. Index [geometry][budget]. Exact overapprox:
 // /3 divisibility is relaxed but multiplication by inverse 3 mod 64 preserves every exact predecessor.
 const int MOD=64,INV3=43;std::vector<uint64_t> bm(G*(B+1),0);auto BIDX=[&](size_t g,int b){return g*(B+1)+b;};auto modR=[&](cpp_int const&v){int x=(int)(v%MOD);if(x<0)x+=MOD;return x;};
 uint64_t bitT=(1ULL<<modR(Jtar));for(int b=0;b<=B;++b)bm[BIDX(idx(n0,zt,1),b)]=bitT;
 uint64_t mapbit[4][32][64]{}; // edge,d,res -> predecessor bit; d<=DMAX
 for(int d=1;d<=DMAX;++d)for(int e=0;e<4;++e)for(int r=0;r<64;++r){int x=(e==1||e==3),y=(e==1||e==2);int c=0;if(e==0)c=modR(-Ad[d]);else if(e==1)c=modR(-Bd[d]);else if(e==2)c=modR(-Cd[d]);int pr;if(e==0)pr=(2*r+c)&63;else if(e==1||e==2)pr=(INV3*((2*r+c)&63))&63;else pr=(2*r)&63;mapbit[e][d][r]=(1ULL<<pr);}
 for(int n=n0-1;n>=1;--n)for(int z=1;z<=std::min(zt,n);++z){int pa=n-z;if(pa<0||pa>P-1||!cap[n][z])continue;for(int d=1;d<=DMAX;++d){if(pa+d>P)continue;int cost=d-1;size_t g=idx(n,z,d);for(int b=cost;b<=B;++b){uint64_t out=0;const int xs[4]={0,1,0,1},ys[4]={0,1,1,0};for(int e=0;e<4;++e){int x=xs[e],y=ys[e],nd=d+y-x;if(nd<=0||nd>DMAX)continue;int z2=z+1-x,pa2=pa+x;if(z2<1||z2>zt||pa2>P-1||pa2+nd>P||!cap[n+1][z2])continue;uint64_t sm=bm[BIDX(idx(n+1,z2,nd),b-cost)];while(sm){int r=__builtin_ctzll(sm);sm&=sm-1;out|=mapbit[e][d][r];}}bm[BIDX(g,b)]=out;}}}
 if(!(bm[BIDX(idx(1,1,1),B)]&(1ULL<<modR(cpp_int(-13))))){R.relaxed_start=false;return R;}
 using Map=std::unordered_map<Key,uint8_t,KH>;std::vector<Map>buckets(n0+1);for(auto&m:buckets)m.max_load_factor(.72);buckets[1][{cpp_int(-13),1,1}]=0;R.total=1;R.peak=1;auto start=std::chrono::steady_clock::now();
 auto future_ok=[&](int nn,int z,int d,cpp_int const&J,int H){if(H>B)return false;int rem=B-H;uint64_t mask=bm[BIDX(idx(nn,z,d),rem)];return (mask&(1ULL<<modR(J)))!=0;};
 auto put=[&](int nn,int z,int d,cpp_int J,int H){if(nn<1||nn>n0||z<1||z>zt)return;int pa=nn-z;if(pa<0||pa>P-1||pa+d>P||!cap[nn][z])return;if(H>B||H+d*(d-1)/2>B)return;Hull const&hh=hull[idx(nn,z,d)];if(!hh.ok||J<hh.lo||J>hh.hi){++R.hull_prune;return;}if(!future_ok(nn,z,d,J,H)){++R.res_prune;return;}if(nn==n0){if(z==zt&&d==1&&J==Jtar){R.hit=true;if(R.minH<0||H<R.minH)R.minH=H;}return;}auto&m=buckets[nn];Key k{std::move(J),(uint16_t)z,(uint8_t)d};auto it=m.find(k);if(it==m.end())m.emplace(std::move(k),(uint8_t)H);else if(H<it->second)it->second=(uint8_t)H;};
 for(int n=1;n<n0;++n){Map cur;cur.swap(buckets[n]);if(cur.empty())continue;R.peak=std::max<uint64_t>(R.peak,cur.size());R.total+=cur.size()-(n==1?1:0);for(auto const&kv:cur){int z=kv.first.z,d=kv.first.d,H=kv.second;cpp_int J=kv.first.J;if(d==1){if(!(J&1)){if(n+1<=n0){cpp_int J2=(3*J+Cd[1])/2;put(n+1,z+1,2,std::move(J2),H);}continue;}++R.macro_starts;int nn=n,zz=z;cpp_int jj=J;while(nn<n0&&(jj&1)){int mod4=(int)(jj&3);int xc=(mod4==1)?0:1,xe=1-xc;int zexit=zz+1-xe;cpp_int je;if(xe==0)je=(jj+Ad[1])/2;else je=(3*jj+Bd[1])/2;if(nn+1==n0)put(nn+1,zexit,1,je,H);else{int ne=nn+1,ze=zexit,pe=ne-ze;if(ne<n0&&ze>=1&&ze<=zt&&pe>=0&&pe<=P-1&&pe+1<=P&&cap[ne][ze]){Hull const&he=hull[idx(ne,ze,1)];if(he.ok&&je>=he.lo&&je<=he.hi&&future_ok(ne,ze,1,je,H)){cpp_int j2=(3*je+Cd[1])/2;put(ne+1,ze+1,2,std::move(j2),H);}else ++R.hull_prune;}}
 int zc=zz+1-xc;cpp_int jc;if(xc==0)jc=(jj+Ad[1])/2;else jc=(3*jj+Bd[1])/2;int n2=nn+1,pa2=n2-zc;++R.macro_steps;if(n2>n0||zc<1||zc>zt||pa2<0||pa2>P-1||pa2+1>P||!cap[n2][zc])break;Hull const&hc=hull[idx(n2,zc,1)];if(!hc.ok||jc<hc.lo||jc>hc.hi){++R.hull_prune;break;}if(!future_ok(n2,zc,1,jc,H)){++R.res_prune;break;}nn=n2;zz=zc;jj=std::move(jc);}continue;}
 if(J&1){int nh=H+d-1;put(n+1,z+1,d,(J+Ad[d])/2,nh);put(n+1,z,d,(3*J+Bd[d])/2,nh);}else{int nh=H+d-1;put(n+1,z+1,d+1,(3*J+Cd[d])/2,nh);if(d>1)put(n+1,z,d-1,J/2,nh);}}}
 R.secs=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();return R;}
int main(int argc,char**argv){if(argc!=4){std::cerr<<"usage A ELL t\n";return 2;}auto r=run_t(std::stoi(argv[1]),std::stoi(argv[2]),std::stoi(argv[3]));int t=std::stoi(argv[3]);if(!r.terminal_cap){std::cout<<"t "<<t<<" terminal_cap_false\n";return 0;}if(!r.relaxed_start){std::cout<<"t "<<t<<" future_relaxation_excludes_start\n";return 0;}std::cout<<"t "<<t<<" total "<<r.total<<" peak "<<r.peak<<" macro_starts "<<r.macro_starts<<" macro_steps "<<r.macro_steps<<" hull_prune "<<r.hull_prune<<" res_prune "<<r.res_prune<<" hit "<<(r.hit?1:0)<<" minH "<<r.minH<<" secs "<<r.secs<<"\n";return r.hit?1:0;}
