#!/usr/bin/env python3
from fractions import Fraction
from collections import defaultdict
from functools import lru_cache

A=217_976_794_617
L=137_528_045_312
p=65_470_613_321
u=103_768_467_013
B=A-L
R=L-B
GAP_LOWER=128_081_997_553
GAP_UPPER=293_591_818_782
K_LO=128_081_997_553
CLEAN=10_075_174_499
N35=7_559_400_754
N36=7_238_318_174
N37=7_052_720_272
U=Fraction(1,2**25)

assert A*p-L*u==1

def ceil_div(a,b): return (a+b-1)//b
def v2(x): return (x & -x).bit_length()-1
def cbit(r): return 1 if r<R else 2

def ln_bounds_int(x,N=100):
    x=Fraction(x)
    z=(x-1)/(x+1)
    z2=z*z
    term=z
    s=Fraction(0)
    for n in range(N):
        s += term/Fraction(2*n+1)
        term *= z2
    lo=2*s
    tail=2*term/Fraction(2*N+1)/(1-z2)
    return lo,lo+tail

@lru_cache(maxsize=None)
def exp_bounds_pos(x,N=50):
    assert 0<=x<1
    term=Fraction(1)
    s=term
    for k in range(1,N+1):
        term=term*x/k
        s += term
    nxt=term*x/Fraction(N+1)
    tail=nxt/(1-x/Fraction(N+2))
    return s,s+tail

l2_lo,l2_hi=ln_bounds_int(2)
l3_lo,l3_hi=ln_bounds_int(3)
d_lo=A*l2_lo-L*l3_hi
d_hi=A*l2_hi-L*l3_lo
s_lo=p*l3_lo-u*l2_hi
s_hi=p*l3_hi-u*l2_lo
assert 0<d_lo<d_hi<Fraction(1,1000)
assert 0<s_lo<s_hi<Fraction(1,1000)

@lru_cache(maxsize=None)
def exp_hi_at_rank(r):
    q=(p*r)//L
    xhi=r*s_hi+q*d_hi
    return exp_bounds_pos(xhi)[1]

def local_budget_U(T,H,rhi):
    generic=Fraction(2**(24-H),1)
    corridor=Fraction(K_LO*(2**25),T)
    rank_endpoint=Fraction(2**(25-H),1)/exp_hi_at_rank(rhi)
    return max(generic,corridor,rank_endpoint)

late_max={j:(0 if j==0 else ceil_div(j*B,L)) for j in range(40)}
height_envelope={j:1+late_max[j] for j in range(40)}
rows=defaultdict(list)
for tau in range(26,40):
    ell0=(tau*B)//L
    ell1=ceil_div(tau*B,L)
    for h0 in (0,1):
        lo=GAP_LOWER*(2**h0)
        hi=GAP_UPPER*(2**h0)
        step=2**tau
        for k in range(lo//step+1,(hi-1)//step+1):
            C0=k*step
            vv=v2(C0)
            odd=C0>>vv
            T=(3**tau)*odd
            for ell in sorted({ell0,ell1}):
                H=h0+tau+ell-vv
                if H<1 or H>height_envelope[tau]:
                    continue
                if not (GAP_LOWER*(2**H)<T<GAP_UPPER*(2**H)):
                    continue
                rlo=max(0,tau*B-ell*L)
                rhi=min(L-1,tau*B-(ell-1)*L-1)
                if rlo<=rhi:
                    rows[(T,H)].append((tau,h0,C0,vv,odd,ell,rlo,rhi))

def word_before_terminal(r_terminal,n):
    return tuple(cbit((r_terminal-(n-j)*B)%L) for j in range(n))

def backward_gaps(word,terminal):
    ds=[None]*(len(word)+1)
    ds[-1]=terminal
    for j in range(len(word)-1,-1,-1):
        ds[j]=ds[j+1]*(2**word[j])/3
    return tuple(ds)

def full_prefix_core(rawlo,rawhi,tau,terminal):
    bounds={rawlo,rawhi+1}
    for j in range(tau):
        shift=(tau-j)*B
        for threshold in (0,R):
            q=(threshold+shift)%L
            if rawlo<q<=rawhi:
                bounds.add(q)
    bounds=sorted(bounds)
    good=[]
    for x,y in zip(bounds,bounds[1:]):
        lo,hi=x,y-1
        if lo>hi:
            continue
        w=word_before_terminal(lo,tau)
        assert word_before_terminal(hi,tau)==w
        ds=backward_gaps(w,terminal)
        if all(Fraction(GAP_LOWER)<d<Fraction(GAP_UPPER) for d in ds):
            good.append((lo,hi))
    merged=[]
    for lo,hi in good:
        if merged and merged[-1][1]+1==lo:
            merged[-1]=(merged[-1][0],hi)
        else:
            merged.append((lo,hi))
    return merged

core_by_key_tau={}
for (T,H),rs in rows.items():
    terminal=Fraction(T,2**H)
    dct=defaultdict(list)
    for rr in rs:
        dct[rr[0]].extend(full_prefix_core(rr[-2],rr[-1],rr[0],terminal))
    md={}
    for tau,cs in dct.items():
        merged=[]
        for a,b in sorted(cs):
            if merged and a<=merged[-1][1]+1:
                merged[-1]=(merged[-1][0],max(merged[-1][1],b))
            else:
                merged.append((a,b))
        md[tau]=merged
    core_by_key_tau[(T,H)]=md

cells=[]
for (T,H),md in core_by_key_tau.items():
    points={0,L}
    for cs in md.values():
        for a,b in cs:
            points.add(a)
            points.add(b+1)
    ss=sorted(points)
    for a,b1 in zip(ss,ss[1:]):
        b=b1-1
        if a>b:
            continue
        owners=tuple(sorted(t for t,cs in md.items() if any(x<=a and b<=y for x,y in cs)))
        if owners:
            cells.append((T,H,a,b,owners))
cells=sorted(cells)
assert len(cells)==7531


# Frozen exact recurrence certificates were generated by the companion deep
# verifier and are recorded in DEEP_RECURRENCE_OUTPUT.txt. The fast suite
# rechecks all deterministic consequences, caps, the 7,531-cell coverage
# surface, and the final saturation arithmetic without re-running 278,049
# large carry-word atoms.
cap210=L//210
cap5597=L//5597
cap3032=L//3032
cap1001=L//1001
assert cap210==654_895_453
assert cap5597==24_571_742
assert cap3032==45_358_853
assert cap1001==137_390_654

target=(216_803_362_095_665_397,20,62_456_644_959,96_166_487_667,(32,33,34))
h20six=(150_094_635_296_999_121,20,0,18_406_412_838,(31,32,33,34,35,36))
h20four=(250_157_725_494_998_535,20,96_166_487_668,98_855_162_143,(32,33,34,35))
h21a=(350_220_815_692_997_949,21,23_369_453_298,41_775_866_136,(33,34,35))
h21b=(450_283_905_890_997_363,21,72_797_034_370,103_818_202_602,(34,35,36,37))
newh21=(550_346_996_088_996_777,21,109_195_551_555,122_224_615_441,(34,35))
h24=(4_052_555_153_018_976_267,24,96_166_487_668,111_884_226_030,(39,))
for c0 in (target,h20six,h20four,h21a,h21b,newh21,h24):
    assert c0 in cells

c=local_budget_U(h24[0],h24[1],h24[3])
a=local_budget_U(target[0],target[1],target[3])/3
b_corner=(local_budget_U(h20six[0],h20six[1],h20six[3])-4*a)/2
b=local_budget_U(newh21[0],newh21[1],newh21[3])-a
assert b>b_corner>c>0
assert 4*a+2*b_corner==local_budget_U(h20six[0],h20six[1],h20six[3])
assert a+b==local_budget_U(newh21[0],newh21[1],newh21[3])

def charge_U(owners):
    return sum(a if t<=34 else b if t in (35,36) else c for t in owners)

generic_over=[]
for cell in cells:
    T,H,rlo,rhi,owners=cell
    if charge_U(owners)>Fraction(2**(24-H),1):
        generic_over.append(cell)
assert len(generic_over)==17

over=[]
binding=[]
for cell in generic_over:
    T,H,rlo,rhi,owners=cell
    ch=charge_U(owners)
    bud=local_budget_U(T,H,rhi)
    if ch>bud:
        over.append(cell)
    elif ch==bud:
        binding.append(cell)

expected_over=[h20six,h20four,h21a,h21b]
expected_binding=[target,newh21,h24]
assert over==sorted(expected_over)
assert binding==sorted(expected_binding)

caps={
    h20six:cap5597,
    h20four:cap3032,
    h21a:cap1001,
    h21b:cap1001,
}
penalty=Fraction(0)
for cell in over:
    T,H,rlo,rhi,owners=cell
    penalty += (charge_U(owners)-local_budget_U(T,H,rhi))*caps[cell]

early=CLEAN-N35
middle=(N35-N36)+(N36-N37)
late=N37
assert early==2_515_773_745
assert middle==506_680_482
assert late==7_052_720_272

ordinary=U*(early*a+middle*b+late*c-penalty)
assert ordinary>Fraction(7_424_232,10_000)
assert ordinary/2>Fraction(3_712_116,10_000)
assert ordinary/6>Fraction(1_237_372,10_000)

slope_b=middle-cap3032-2*cap5597-cap1001-2*cap1001
assert slope_b==6183
assert slope_b-6182>0
assert slope_b-6183==0
threshold=L//6183+1
assert threshold==22_242_932
assert L//(threshold-1)==6183
assert L//threshold==6182

# Promoted H21 returnability certificate: spacing >=3032, cap 45358853.
# It is deliberately not used to cross the new binding cell because the
# required cap for strict further gain is <=6182.
assert cap3032>6182

print("PASS: RL237 fast 7,531-cell charging / saturation verifier")
print("full_prefix_atomic_cells=7531")
print("generic_overage_candidates=17")
print("final_overbudget_cells=4 final_binding_cells=3")
print("H20_323334_cap_from_spacing210=654895453")
print("H20_3136_cap_from_spacing5597=24571742")
print("H21_3435_returnability_cap_from_spacing3032=45358853")
print("final_early_charge_U_approx=%.12f" % float(a))
print("final_middle_charge_U_approx=%.12f" % float(b))
print("final_late_charge_U_approx=%.12f" % float(c))
print("ordinary_abs_flow_approx=%.12f" % float(ordinary))
print("ordinary_abs_flow_gt_742_4232=yes")
print("each_signed_flow_gt_371_2116=yes")
print("each_directional_K_variation_gt_123_7372=yes")
print("uncapped_H21_3435_crossing_slope_before_cap=6183")
print("H21_3435_cap_needed_le=6182")
print("H21_3435_spacing_needed_for_further_charge=22242932")
print("charging_program_frozen_for_RL238_pivot=yes")
